### ISSUE TITLE
Thumbnail on seekbar isn't working.

### ISSUE THREAD

**Issue by sagarnasit** [jronallo/mep-feature-time-rail-thumbnails#2]
Please provide detailed documentation to add this feature with mediaelement.js.
The site you referred which is using this doesn't show thumbnails on seek-bar hover anymore.
May be new mediaelement.js version isn't supported.

**Comment by jronallo** [comment]
This repository is now unmaintained. I'm sorry I didn't list it as that sooner. We're working on a new video player based on video.js that will have this feature.
